amhsystem/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('medicine/', include('medicine.urls')),
    path('records/', include('records.urls')),
    path('pdfs/', include('pdfs.urls')),
    path('appointment/', include('appointment.urls')),
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    # Auth
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),

    path('', views.home, name='home'),

    # Patients related
    path('allpatients/', views.allpatients, name='allpatients'),
    path('searchpatient/', views.searchpatient, name='searchpatient'),
    path('addpatient/', views.addpatient, name='addpatient'),
    path('viewpatient/<int:patient_pk>', views.viewpatient, name='viewpatient'),
    path('editpatient/<int:patient_pk>', views.editpatient, name='editpatient'),
    path('deletepatient/<int:patient_pk>', views.deletepatient, name='deletepatient'),
    path('fetchpatientnames', views.fetchpatientnames, name='fetchpatientnames'),

]

main/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinLengthValidator, MinValueValidator

# Create your models here.
class PatientCategory(models.TextChoices):
    ANC = 'ANC'
    INF = 'INF'
    GYNAC = 'GYNAC'
class PatientGender(models.TextChoices):
    MALE = 'Male' 
    FEMALE = 'Female'
class Patient(models.Model):
    category = models.CharField(max_length=5, choices=PatientCategory.choices, default=PatientCategory.ANC)
    case_paper_number = models.CharField(max_length=20)
    full_name = models.CharField(max_length=100, validators=[MinLengthValidator(10)])
    age = models.IntegerField(blank=False, validators=[MinValueValidator(12), MaxValueValidator(65)])
    birth_date = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=10, choices=PatientGender.choices, default=PatientGender.FEMALE)
    mobile_number = models.CharField(max_length=12)
    email = models.EmailField(blank=True)
    address_line_1 = models.CharField(max_length=100, blank=True)
    address_line_2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=50, blank=False)
    pin_code = models.IntegerField(blank=True, null=True)
    referred_by = models.CharField(max_length=100, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    is_inf = models.BooleanField(default=False)
    is_anc = models.BooleanField(default=False)
    is_gynac = models.BooleanField(default=False)
    def __str__(self):
        return self.full_name

main/forms.py
from django.forms import ModelForm, widgets
from .models import Patient

class AddPatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = [
            'category', 
            'case_paper_number', 
            'full_name', 
            'age', 
            'birth_date', 
            'gender', 
            'mobile_number', 
            'email', 
            'address_line_1', 
            'address_line_2', 
            'city', 
            'pin_code', 
            'referred_by',
        ]
        widgets = {
            # 'birth_date': widgets.Input(attrs={'autocomplete':'off'}),
            'birth_date': widgets.DateInput(format= '%d-%m-%Y', attrs={'class':'form-control', 'autocomplete':'off', 'placeholder': 'dd-mm-yyyy'}),
            'mobile_number': widgets.NumberInput(attrs={'type': 'number'}),
            'email': widgets.EmailInput(),
            'pin_code': widgets.NumberInput(attrs={'required': 'required'}),
         }

class EditPatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = [
            'case_paper_number', 
            'full_name', 
            'age', 
            'birth_date', 
            'gender', 
            'mobile_number', 
            'email', 
            'address_line_1', 
            'address_line_2', 
            'city', 
            'pin_code', 
            'referred_by',
            'is_anc',
            'is_inf',
            'is_gynac'
        ]
        widgets = {
            # 'birth_date': widgets.Input(attrs={'autocomplete':'off'}),
            'birth_date': widgets.DateInput(format= '%d-%m-%Y', attrs={'class':'form-control', 'autocomplete':'off', 'placeholder': 'dd-mm-yyyy'}),
            'mobile_number': widgets.NumberInput(attrs={'type': 'number'}),
            'email': widgets.EmailInput(),
            'pin_code': widgets.NumberInput(attrs={'required': 'required'}),
         }

main/views.py
from appointment.models import Appointment
from main.models import Patient
from django.shortcuts import render
from datetime import datetime
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import date
from .forms import *

def loginuser(request): 
    if request.method == 'GET':
        return render(request, 'main/loginuser.html', {'login_form': AuthenticationForm() })
    else:
        #  Login user if allowed
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'main/loginuser.html', {'form':AuthenticationForm(), 'error':'Username and password did not match'})
        else:
            login(request, user)
            return redirect('home')


@login_required(login_url='loginuser')
def home(request):
    # pass number of patients
    patientcount = Patient.objects.count()

    # Pass today's appointments
    todaysapts = []
    today = date.today()
    todaydate = today.strftime("%Y-%m-%d")
    todayAptSet = Appointment.objects.filter(on_date = todaydate)
    todayaptscount = Appointment.objects.filter(on_date = todaydate).count()
    
    if request.method == 'GET':
        for apt in todayAptSet:
            todaysapts.append(apt)
        return render(request, 'main/home.html', {
            'appointments': todaysapts, 
            'selectedDateStr': '', 
            'todayaptscount': todayaptscount, 
            'patientcount': patientcount})

    elif 'aptsbydate' in request.POST:
        selectedDateStr = request.POST['datepicker']
        selectedDate = datetime.strptime(selectedDateStr, '%d-%m-%Y')
        aptsSet = Appointment.objects.filter(on_date = selectedDate)
        return render(request, 'main/home.html', {
            'appointments': aptsSet, 
            'selectedDateStr': selectedDateStr,
            'todayaptscount': todayaptscount, 
            'patientcount': patientcount })

def logoutuser(request):
    if request.method == 'GET':
        logout(request)
        return redirect('loginuser')

def searchpatient(request):
    query = request.GET['query']
    patientlistbyname = Patient.objects.filter(full_name__icontains=query)
    patientlistbynumber = Patient.objects.filter(
        case_paper_number__icontains=query)
    patientlist = patientlistbyname.union(patientlistbynumber)
    if patientlist.count() == 1:
        messages.add_message(request, messages.SUCCESS, str(patientlist.count()) + ' Patient Found!')
    elif patientlist.count() == 0:
        pass
    else:
        messages.add_message(request, messages.SUCCESS, str(patientlist.count()) + ' Patients Found!')
    return render(request, 'main/allpatients.html', {'patients': patientlist})

@login_required(login_url='loginuser')
def allpatients(request):
    if request.method == 'GET':
        patients = Patient.objects.order_by('id').reverse()
        return render(request, 'main/allpatients.html', {'patients': patients})

@login_required(login_url='loginuser')
def addpatient(request):
    form = AddPatientForm()
        # Get last case paper number and set next to case paper number input 
    last_number = None
    casepapernumber = 'ANC-1' 
    last_patient = Patient.objects.last()
    if last_patient:
        last_number = last_patient.case_paper_number
        hyphenindex = last_number.index('-')
        numberstring = last_number[hyphenindex + 1:]
        number = int(numberstring)
        casepapernumber = 'ANC-' + str(number + 1)

    if request.method == 'GET':
        return render(request, 'main/addpatient.html', {'casepapernumber': casepapernumber, 'form':form})
        
    elif request.method=='POST':
        form = AddPatientForm(request.POST) 
        try:
            if form.is_valid():
                newpatient = form.save(commit=False)
                if form.cleaned_data['category'] == 'ANC':
                    newpatient.is_anc = True
                if form.cleaned_data['category'] == 'INF':
                    newpatient.is_inf = True
                if form.cleaned_data['category'] == 'GYNAC':
                    newpatient.is_gynac = True
                newpatient.save() 
                patients = Patient.objects.order_by('id').reverse()
                messages.add_message(request, messages.SUCCESS, 'Patient Added Successfully!')
                return render(request, 'main/allpatients.html', {'patients': patients})
            else:
                return render (request, 'main/addpatient.html', {'casepapernumber': casepapernumber, 'form':form})
        except ValueError:
            messages.add_message(request, messages.ERROR, 'Please submit valid data!')
            return render(request, 'main/addpatient.html', {'casepapernumber': casepapernumber, 'form':form})

@login_required(login_url='loginuser')        
def viewpatient(request, patient_pk):
    if request.method == 'GET':
        patient = get_object_or_404(Patient, pk=patient_pk)
        return render(request, 'main/viewpatient.html', {'patient': patient})

@login_required(login_url='loginuser')
def editpatient(request, patient_pk):
    patient = get_object_or_404(Patient, pk=patient_pk)
    if request.method == 'GET':
        editpatientform = EditPatientForm(instance=patient)
        return render(request, 'main/editpatient.html', {'patient': patient, 'form': editpatientform})
    elif request.method == 'POST':
        form = EditPatientForm(request.POST, instance=patient)
        try:
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Patient updated successfully!')
                return render(request, 'main/editpatient.html', {'patient': patient, 'form': form})
        except ValueError:
            messages.add_message(request, messages.ERROR, 'Please submit valid data!')
            return render(request, 'main/editpatient.html', {'patient': patient, 'form':form})

@login_required(login_url='loginuser')
@permission_required('main.delete_patient')
def deletepatient(request, patient_pk):
    try:
        patient = get_object_or_404(Patient, pk=patient_pk)
        patient.delete()
        messages.add_message(request, messages.SUCCESS, 'Patient deleted successfully!')
        return redirect('allpatients')
    except:
        messages.add_message(request, messages.ERROR, 'Something went wrong! Try again later!')
        return redirect('allpatients')



def fetchpatientnames(request):
    if 'term' in request.GET:
        term = request.GET.get('term')
        patients = Patient.objects.filter(full_name__icontains=term)
        names = list()
        print(names)
        for patient in patients:
            names.append(patient.full_name)
        return JsonResponse(names, safe=False)

templates/main/addpatient.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-xl-10 col-lg-10">
        <div class="card shadow mb-4 mt-5 ml-5 p-4">
            <!-- Card Header  -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h3 class="m-0 font-weight-bold text-primary">Add Patient</h3>
            </div>

            <!-- Card Body -->
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}

                    {% if messages %}
                    {% for message in messages %}
                    <div class="row justify-content-md-center">
                        <div class="alert alert-danger col-md-auto" role="alert">
                            {{ message }}
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <div class="row mt-3 border border-info p-4 border-left-info">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="form-group col-md-3">
                                    {{ form.category|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.case_paper_number|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.gender|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-md-3">
                                    {{ form.full_name|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.birth_date|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.age|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-md-3">
                                    {{ form.address_line_1|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.address_line_2|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.city|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    {{ form.pin_code|as_crispy_field }}
                                </div>
                                <div class="form-group col-md-3">
                                    {{ form.mobile_number|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.email|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    {{ form.referred_by|as_crispy_field }}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">SAVE</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}

{% block jquery %}
<script>
    $(document).ready(function () {

        //  change date format for birth date input
        $("#id_birth_date").datepicker({
            format: 'dd-mm-yyyy',
        });

        // Change category checkboxes when category select is changed
        // set case paper number on category change
        $('#anc').prop('checked', true);

        var wholenumber = '{{ casepapernumber }}';
        var number = wholenumber.substring(wholenumber.indexOf('-') + 1, wholenumber.length);
        $('#id_case_paper_number').val('ANC-' + number);

        $('select[name="category"]').change(function () {
            if ($(this).val() == "ANC") {
                $('#id_case_paper_number').val('ANC-' + number);
            }
            if ($(this).val() == "INF") {
                $('#id_case_paper_number').val('INF-' + number);
            }
            if ($(this).val() == "GYNAC") {
                $('#id_case_paper_number').val('GYNAC-' + number);
            }
        });


        // Set and change full name input's text as Mr. OR Mrs.
        $('#id_full_name').val('Mrs. ');
        $('#id_gender').change(function () {
            if (this.value == 'M') {
                $('#id_full_name').val('Mr. ');
            }
            else if (this.value == 'F') {
                $('#id_full_name').val('Mrs. ');
            }
        });

        // Calculate the age based on the birthdate
        $('#id_birth_date').change(function () {
            var today = new Date();
            var birthDate = new Date(this.value);
            var age = today.getFullYear() - birthDate.getFullYear();
            var m = today.getMonth() - birthDate.getMonth();
            if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
                age--;
            }
            $('#id_age').val(age);
        })


    });
</script>
{% endblock %}

templates/main/allpatients.html
{% extends "base.html" %} {% block content %}
{% load static %}
{% block css %}
{% endblock css %}
<div class="row">
    <div class="col-xl-10 col-lg-10">
        <div class="card shadow mb-4 mt-5 ml-5 p-4">
            <!-- Card Header  -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h3 class="m-0 font-weight-bold text-primary">All Patients
                    {% if patients %}
                    <small>
                        ({{ patients.count}})
                    </small>
                    {% endif %}
                </h3>

                <div class="col-sm-3 mt-2 d-flex flex-row justify-content-end">
                    <form action="{% url 'addpatient' %}" method="GET">
                        <button class="btn btn-danger"><i class="fas fa-plus pr-2"></i>ADD NEW</button>
                    </form>
                </div>
            </div>
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-success col-md-auto" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}

                {% if patients %}
                <div class="table-responsive">

                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Patient Name</th>
                                <th>Mobile</th>
                                <th>City</th>
                                <th>Date Added</th>
                                <th>Actions</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for patient in patients %}
                            <tr>
                                <td>{{patient.case_paper_number}}</td>
                                <td>{{patient.full_name}}</td>
                                <td>{{patient.mobile_number}}</td>
                                <td>{{patient.city}}</td>
                                <td>{{patient.date_added|date:"M d, Y"}}</td>
                                <td>
                                    <form action="{% url 'viewpatient' patient.id %}" method="GET">
                                        <button type="submit" class="btn btn-primary btn-sm"
                                            name="view">View/Edit</button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <div class="text-center">
                    <h2>No Patients Found!</h2>
                    <br>
                    <a role="button" class="btn btn-primary" href="{% url 'addpatient' %}">New Patient</a>
                </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block jquery %}
<!-- Page level plugins -->
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/datatables-demo.js' %}"></script>
{% endblock jquery %}

templates/main/editpatient.html
{% extends "base.html" %} {% load static %}
{% load crispy_forms_tags %}{% block content %}

<div class="row">
    <div class="col-xl-10 col-lg-10">
        <div class="card shadow mb-4 mt-5 ml-5 p-4">
            <!-- Card Header  -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h2 class="m-0 font-weight-bold text-primary">Edit Patient ({{ patient.full_name }})</h2>
                <form action="{% url 'viewpatient' patient.id %}" method="GET">
                    <button class="btn btn-warning"><i class="fas fa-arrow-left pr-3"></i>BACK</button>
                </form>
            </div>

            <!-- Card Body -->
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-danger col-md-6" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}


                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row mt-3">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="form-group col-md-3">
                                    {{ form.full_name|as_crispy_field }}
                                    {{ form.address_line_1|as_crispy_field }}
                                    {{ form.pin_code|as_crispy_field }}
                                    {{ form.referred_by|as_crispy_field }}
                                    {{ form.is_anc|as_crispy_field }}
                                    {{ form.is_inf|as_crispy_field }}
                                    {{ form.is_gynac|as_crispy_field }}
                                </div>
                                <div class="form-group col-md-3">
                                    {{ form.case_paper_number|as_crispy_field }}
                                    {{ form.gender|as_crispy_field }}
                                    {{ form.address_line_2|as_crispy_field }}
                                    {{ form.mobile_number|as_crispy_field }}

                                </div>
                                <div class="form-group col-md-3">
                                    {{ form.age|as_crispy_field }}
                                    {{ form.birth_date|as_crispy_field }}
                                    {{ form.city|as_crispy_field }}
                                    {{ form.email|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-md-6">

                                </div>
                            </div>
                            <button type="submit" class="btn btn-danger mt-3">UPDATE</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %} {% block jquery %}
<script>
    $(document).ready(function () {
        $("#id_birth_date").datepicker({
            format: 'dd-mm-yyyy',
        });
    });
</script>
{% endblock %}

templates/main/home.html
{% extends 'base.html' %}

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">HOME</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-download fa-sm text-white-50"></i> Print Records</a>
</div>

<div class="row">
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Total Patients</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ patientcount }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Today's Appointments</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ todayaptscount }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<!-- Appointments view -->
<div class="row">

    <div class="col-xl-6 col-lg-6">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Appointments</h6>

            </div>
            <!-- Card Body -->

            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <label for="datepicker">Select Date</label>

                    <div class="d-flex">
                        <div class="input-group" style="width: 30%;">
                            <input type="text" class="form-control" id='datepicker' name='datepicker'>
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm ml-3" name='aptsbydate'>SEE
                            APPOINTMENTS</button>
                    </div>
                </form>

                {% if appointments %}
                <div class="apt-list">
                    <h6 class="text-info mt-5 mb-3" id="date-heading">Appointments on <b>{{ selectedDateStr }}</b></h6>
                    <table class="table table-borderless">
                        <thead>
                            <tr>
                                <th scope="col">Patient Name</th>
                                <th scope="col">Date</th>
                                <th scope="col">Reason</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for appointment in appointments %}
                            <tr>
                                <td>{{ appointment.patient_name }}</td>
                                <td>{{ appointment.on_date }}</td>
                                <td>{{ appointment.reason }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    {% else %}
                    <h6 class="text-info mt-5"><b>No appointments!</b></h6>
                </div>
                {% endif %}
            </div>
        </div>
    </div>


</div>
{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function () {

        $("#datepicker").datepicker({
            format: 'dd-mm-yyyy',
        });

        // set date picker value to today
        datestr = '{{ selectedDateStr }}'
        if (datestr == '') {
            var now = new Date();
            var day = ("0" + now.getDate()).slice(-2);
            var month = ("0" + (now.getMonth() + 1)).slice(-2);
            var today = (day) + "-" + (month) + "-" + (now.getFullYear());

            $('#datepicker').val(today);
            $('#date-heading').text('Appointments on ' + today)
        } else {
            $('#datepicker').val(datestr);
        }


    });
</script>
{% endblock %}