amhsystem/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('medicine/', include('medicine.urls')),
    path('records/', include('records.urls')),
    path('pdfs/', include('pdfs.urls')),
    path('appointment/', include('appointment.urls')),
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    # Auth
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),

    path('', views.home, name='home'),

    # Patients related
    path('allpatients/', views.allpatients, name='allpatients'),
    path('searchpatient/', views.searchpatient, name='searchpatient'),
    path('addpatient/', views.addpatient, name='addpatient'),
    path('viewpatient/<int:patient_pk>', views.viewpatient, name='viewpatient'),
    path('editpatient/<int:patient_pk>', views.editpatient, name='editpatient'),
    path('deletepatient/<int:patient_pk>', views.deletepatient, name='deletepatient'),
    path('fetchpatientnames', views.fetchpatientnames, name='fetchpatientnames'),

]

records/urls.py
from django.urls import path
from records import views

urlpatterns = [
    path('<int:patient_pk>/ancfirstblock', views.ancfirstblock, name='ancfirstblock'),
    path('<int:patient_pk>/ancotherblocks/<int:visit_no>', views.ancotherblocks, name='ancotherblocks'),


    path('<int:patient_pk>/infplanonefirstblock', views.infplanonefirstblock, name='infplanonefirstblock'),
    path('<int:patient_pk>/infplantwofirstblock', views.infplantwofirstblock, name='infplantwofirstblock'),
    path('<int:patient_pk>/infplanoneotherblocks/<int:visit_no>', views.infplanoneotherblocks, name='infplanoneotherblocks'),
    path('<int:patient_pk>/infplantwootherblocks/<int:visit_no>', views.infplantwootherblocks, name='infplantwootherblocks'),


    path('<int:patient_pk>/gynacfirstblock', views.gynacfirstblock, name='gynacfirstblock'),
    path('<int:patient_pk>/gynacotherblocks/<int:visit_no>', views.gynacotherblocks, name='gynacotherblocks'),


    path('<int:patient_pk>/investigations', views.investigations, name='investigations'),
    path('<int:patient_pk>/usg', views.usg, name='usg'),
    path('<int:patient_pk>/ttdose', views.ttdose, name='ttdose'),
    path('<int:patient_pk>/fertilitysheet', views.fertilitysheet, name='fertilitysheet'),
    path('<int:patient_pk>/malehistory', views.malehistory, name='malehistory'),
    path('<int:patient_pk>/wifeexams', views.wifeexams, name='wifeexams'),
]

appointment/models.py
from django.db import models
from django.db.models.fields import TimeField
from main.models import Patient

# Create your models here.
class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    patient_name = models.CharField(max_length=150)
    date_added = models.DateTimeField(auto_now_add=True)
    on_date = models.DateField(blank=False)
    visit_no = models.IntegerField(blank=True, null=True)
    # at_time = models.TimeField(blank=True, null=True)
    reason = models.CharField(max_length=100, blank=True)

records/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinLengthValidator, MinValueValidator
from django.db.models.fields import CharField
from main.models import Patient

# Create your models here.
class FertilitySheet(models.Model):
    class CycleValue(models.TextChoices):
        _21_To_25 = '21-25'
        _28_To_35 = '28-35'
        _45_To_60 = '45-60'
        _60_To_90 = '60-90'
        _90_To_120 = '90-120'
        Beyond_120 = 'Beyond 120'
        Need_Rx = 'Need Rx'
    
    class MC(models.TextChoices):
        regular = 'Regular'
        irregular = 'Irregular'
    class MedicationNeeded(models.TextChoices):
        yes = 'Yes'
        no = 'No'

    height = models.CharField(max_length=10, blank=True)
    weight = models.CharField(max_length=10, blank=True, null=True)
    bmi = models.CharField(max_length=10, blank=True, null=True)
    trying_for_years = models.CharField(max_length=10, blank=True, null=True)
    trying_for_months = models.CharField(max_length=10, blank=True, null=True)
    menstrual_cycle = models.CharField(max_length=20, choices=MC.choices, default=MC.regular)
    bleeding_days = models.CharField(max_length=10, blank=True, null=True)
    lmp = models.DateField(blank=True, null=True)
    cycle = models.CharField(max_length=20, choices=CycleValue.choices, default=CycleValue._21_To_25)
    medication_needed_for_period = models.CharField(max_length=20, choices=MedicationNeeded.choices, default=MedicationNeeded.no)
    mother_menopause_age = models.FloatField(blank=True, null=True)

    intercourse_per_week = models.IntegerField(default=0)
    intercourse_comment = models.CharField(max_length=150, blank=True)
    is_had_surgery = models.BooleanField(default=False)
    surgery_comment = models.CharField(max_length=200,blank=True)
    is_recent_weight_gain_or_loss = models.BooleanField(default=False)
    is_hair_loss = models.BooleanField(default=False)
    is_asthma = models.BooleanField(default=False)
    is_hepatitis = models.BooleanField(default=False)
    is_anorexia_bulimia = models.BooleanField(default=False)
    is_lumps = models.BooleanField(default=False)
    is_seizures_epilepsy = models.BooleanField(default=False)
    is_vaginal_infections = models.BooleanField(default=False)
    is_diabetes = models.BooleanField(default=False)
    is_tuberculosis = models.BooleanField(default=False)
    is_migraine_headaches = models.BooleanField(default=False)
    is_high_bp = models.BooleanField(default=False)
    is_mother_diabetic = models.BooleanField(default=False)
    is_father_diabetic = models.BooleanField(default=False)
    is_mother_htn = models.BooleanField(default=False)
    is_father_htn = models.BooleanField(default=False)
    physical_symptoms_comment = models.CharField(max_length=150, blank=True)

    laparoscopy_findings = models.TextField(blank=True)
    hsg_findings = models.TextField(blank=True)
    ll_no_of_cycles_1 = models.CharField(max_length=10, blank=True)
    ll_tic_1 = models.CharField(max_length=10, blank=True)
    ll_iui_1 = models.CharField(max_length=10, blank=True)
    ll_pregnant_1 = models.BooleanField(default=False)
    ll_comment_1 = models.CharField(max_length=100, blank=True)
    ll_no_of_cycles_2 = models.CharField(max_length=10, blank=True)
    ll_tic_2 = models.CharField(max_length=10, blank=True)
    ll_iui_2 = models.CharField(max_length=10, blank=True)
    ll_pregnant_2 = models.BooleanField(default=False)
    ll_comment_2 = models.CharField(max_length=100, blank=True)
    ll_no_of_cycles_3 = models.CharField(max_length=10, blank=True)
    ll_tic_3 = models.CharField(max_length=10, blank=True)
    ll_iui_3 = models.CharField(max_length=10, blank=True)
    ll_pregnant_3 = models.BooleanField(default=False)
    ll_comment_3 = models.CharField(max_length=100, blank=True)
    ll_no_of_cycles_4 = models.CharField(max_length=10, blank=True)
    ll_tic_4 = models.CharField(max_length=10, blank=True)
    ll_iui_4 = models.CharField(max_length=10, blank=True)
    ll_pregnant_4 = models.BooleanField(default=False)
    ll_comment_4 = models.CharField(max_length=100, blank=True)
    ivf_comment_I = models.TextField(blank=True)
    ivf_comment_II = models.TextField(blank=True)


    date_added = models.DateTimeField(auto_now_add=True)
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE, null=True)

class MaleMedicalHistory(models.Model):
    husband_name = models.CharField(blank=True, max_length=50)
    husband_age = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(15), MaxValueValidator(60)])
    husband_work = models.CharField(blank=True, max_length=20)
    sperm_count_I = models.FloatField(default=0)
    sperm_count_II = models.FloatField(default=0)
    sperm_count_III = models.FloatField(default=0)
    sperm_motility_I = models.FloatField(default=0)
    sperm_motility_II = models.FloatField(default=0)
    sperm_motility_III = models.FloatField(default=0)
    surgical_dm_htn_comment = models.CharField(blank=True, max_length=200)
    usg_of_scrotum_comment = models.CharField(blank=True, max_length=200)
    fhs_report = models.CharField(max_length=100, blank=True)
    lh_report = models.CharField(max_length=100, blank=True)
    testosterone_report = models.CharField(max_length=100, blank=True)
    hiv_report = models.CharField(max_length=100, blank=True)
    medical_history = models.TextField(blank=True)
    current_rx_husband = models.TextField(blank=True)
    current_rx_wife = models.TextField(blank=True)
    allergic_to = models.TextField(blank=True)
    past_treatment_at_our_clinic = models.TextField(blank=True)
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE, null=True)
    date_added = models.DateTimeField(auto_now_add=True)


class WifeExamination(models.Model):
    amh = models.CharField(max_length=25, blank=True)
    fsh = models.CharField(max_length=25, blank=True)
    lh = models.CharField(max_length=25, blank=True)
    prolactin = models.CharField(max_length=25, blank=True)
    andro = models.CharField(max_length=25, blank=True)
    testo = models.CharField(max_length=25, blank=True)
    tsh = models.CharField(max_length=25, blank=True)
    hb = models.CharField(max_length=25, blank=True)
    sugar = models.CharField(max_length=25, blank=True)
    hba1c = models.CharField(max_length=25, blank=True)
    hiv = models.CharField(max_length=25, blank=True)
    hbsag = models.CharField(max_length=25, blank=True)
    vdrl = models.CharField(max_length=25, blank=True)
    urea = models.CharField(max_length=25, blank=True)
    creat = models.CharField(max_length=25, blank=True)
    lipid_profile = models.CharField(max_length=25, blank=True)
    ac_antibodies = models.CharField(max_length=25, blank=True)
    anti_dsdna = models.CharField(max_length=25, blank=True)
    bg_antibodies = models.CharField(max_length=25, blank=True)
    lupus_anticoagulant = models.CharField(max_length=25, blank=True)
    protein_c = models.CharField(max_length=25, blank=True)
    protein_s = models.CharField(max_length=25, blank=True)
    karyotp = models.CharField(max_length=25, blank=True)
    other = models.CharField(max_length=100, blank=True)
    usg = models.CharField(max_length=100, blank=True)
    lmp = models.DateField(blank=True, null=True)
    day = models.CharField(max_length=100, blank=True)
    plan = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE, null=True)

class Investigation(models.Model):
    date1 = models.DateField(blank=True, null=True)
    date2 = models.DateField(blank=True, null=True)
    date3 = models.DateField(blank=True, null=True)
    hb_on_date1 = models.FloatField(blank=True, null=True)
    hb_on_date2 = models.FloatField(blank=True, null=True)
    hb_on_date3 = models.FloatField(blank=True, null=True)
    bloodGroup = models.CharField(max_length=15, blank=True)
    bslr_on_date1 = models.CharField(max_length=10, blank=True)
    bslr_on_date2 = models.CharField(max_length=10, blank=True)
    bslr_on_date3 = models.CharField(max_length=10, blank=True)
    gct_on_date1 = models.CharField(max_length=10, blank=True)
    gct_on_date2 = models.CharField(max_length=10, blank=True)
    gct_on_date3 = models.CharField(max_length=10, blank=True)
    aust_antg_on_date1 = models.CharField(max_length=10, blank=True)
    aust_antg_on_date2 = models.CharField(max_length=10, blank=True)
    aust_antg_on_date3 = models.CharField(max_length=10, blank=True)
    elisa_on_date1 = models.CharField(max_length=10, blank=True)
    elisa_on_date2 = models.CharField(max_length=10, blank=True)
    elisa_on_date3 = models.CharField(max_length=10, blank=True)
    tsh_on_date1 = models.CharField(max_length=10, blank=True)
    tsh_on_date2 = models.CharField(max_length=10, blank=True)
    tsh_on_date3 = models.CharField(max_length=10, blank=True)
    urine_on_date1 = models.CharField(max_length=10, blank=True)
    urine_on_date2 = models.CharField(max_length=10, blank=True)
    urine_on_date3 = models.CharField(max_length=10, blank=True)
    empty11 = models.CharField(max_length=20, blank=True)
    empty12 = models.CharField(max_length=20, blank=True)
    empty13 = models.CharField(max_length=20, blank=True)
    empty14 = models.CharField(max_length=20, blank=True)
    empty21 = models.CharField(max_length=20, blank=True)
    empty22 = models.CharField(max_length=20, blank=True)
    empty23 = models.CharField(max_length=20, blank=True)
    empty24 = models.CharField(max_length=20, blank=True)
    empty31 = models.CharField(max_length=20, blank=True)
    empty32 = models.CharField(max_length=20, blank=True)
    empty33 = models.CharField(max_length=20, blank=True)
    empty34 = models.CharField(max_length=20, blank=True)
    empty41 = models.CharField(max_length=20, blank=True)
    empty42 = models.CharField(max_length=20, blank=True)

templates/records/infplantwofirstblock.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-xl-10 col-lg-10">
        <div class="card shadow mb-4 mt-5 ml-5 p-4">
            <!-- Card Header  -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h2 class="m-0 font-weight-bold text-primary">CASE PAPER - INF ({{ patient.full_name }})</h2>
                <form action="{% url 'viewpatient' patient.id %}" method="GET">
                    <button class="btn btn-warning"><i class="fas fa-arrow-left pr-3"></i>BACK</button>
                </form>
            </div>

            <!-- Card Body -->
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-danger col-md-6" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}

                <div class="row d-flex justify-content-center flex-row mt-3 mb-4">
                    <div class="btn-1 mr-4">
                        <form action="{% url 'infplanonefirstblock' patient.id %}" method="GET">
                            <button class="btn btn-lg btn-secondary">PLAN I</button>
                        </form>
                    </div>
                    <div class="btn-1">
                        <form action="{% url 'infplantwofirstblock' patient.id %}" method="GET">
                            <button class="btn btn-lg btn-primary">PLAN II</button>
                        </form>
                    </div>
                </div>

                <div class="navigation d-flex flex-row">
                    <div>
                        <form action="{% url 'infplantwofirstblock' patient_pk=patient.id %}" method="get">
                            <button class="btn btn-primary mr-2">
                                Visit 1 <br>
                                {% if ismainform %}
                                <small>{{ mainform.date_added.value }}</small>
                                {% endif %}
                            </button>
                        </form>
                    </div>
                    <div class="d-flex flex-row">
                        {% for otherform in otherforms %}
                        <div>
                            <form
                                action="{% url 'infplantwootherblocks' patient_pk=patient.id visit_no=otherform.visit_no %}"
                                method="get">
                                <button class="btn btn-secondary mr-2">
                                    Visit {{ otherform.visit_no }} <br>
                                    <small>{{ otherform.date_added }}</small>
                                </button>
                            </form>
                        </div>
                        {% endfor %}
                    </div>

                    {% if ismainform %}
                    <div>
                        <form action="{% url 'infplantwootherblocks' patient_pk=patient.id visit_no=newformnumber %}"
                            method="get">
                            <button class="btn btn-danger mr-2">
                                Add New <br>
                                +
                            </button>
                        </form>
                    </div>
                    {% endif %}

                </div>

                <div class="first-block mt-5">
                    <div class="d-flex justify-content-center">
                        <h4 class="text-primary">VISIT - 1</h4>
                    </div>
                    <form action="" method="post">
                        {% csrf_token %}

                        <div class="d-flex justify-content-center">
                            <div class="col-md-12 border border-success p-4 border-left-success">
                                <h6 class="text-success text-center">PLAN II</h6>
                                <h4 class="text-info text-center">Induction on Tablet + Injection</h4>
                                <hr>


                                <div class="first-col d-flex">
                                    <div class="flex-column mt-4 pr-4" style="border-right: 1px dashed #333;">
                                        <div class="d-flex flex-row">
                                            <div class="form-group mr-4">
                                                {{ mainform.date_added|as_crispy_field }}
                                            </div>
                                            <div class="form-group mr-4">
                                                {{ mainform.lmp|as_crispy_field }}
                                            </div>
                                            <div class="form-group">
                                                {{ mainform.days|as_crispy_field }}
                                            </div>
                                        </div>


                                        <div class="d-flex flex-row">
                                            <div class="form-group flex-grow-1 mr-4">
                                                {{ mainform.tablet_name|as_crispy_field }}
                                            </div>
                                            <div class="form-group">
                                                {{ mainform.tablet_qty|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row">
                                            <div class="form-group mr-4">
                                                {{ mainform.tab_morning_qty|as_crispy_field }}
                                            </div>
                                            <div class="form-group mr-4">
                                                {{ mainform.tab_afternoon_qty|as_crispy_field }}
                                            </div>
                                            <div class="form-group">
                                                {{ mainform.tab_evening_qty|as_crispy_field }}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="vertical-line flex-column mr-3 ml-3"></div>

                                    <div class="flex-column mt-4">
                                        <div class="d-flex flex-row">
                                            <div class="form-group mr-4">
                                                {{ mainform.injection_name|as_crispy_field }}
                                            </div>
                                            <div class="form-group mr-4">
                                                {{ mainform.injection_qty|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row">
                                            <div class="form-group mr-4">
                                                {{ mainform.day1|as_crispy_field }}
                                            </div>
                                            <div class="form-group mr-4">
                                                {{ mainform.day2|as_crispy_field }}
                                            </div>
                                            <div class="form-group mr-4">
                                                {{ mainform.day3|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row">
                                            <div class="form-group mr-4">
                                                {{ mainform.date1|as_crispy_field }}
                                            </div>
                                            <div class="form-group mr-4">
                                                {{ mainform.date2|as_crispy_field }}
                                            </div>
                                            <div class="form-group mr-4">
                                                {{ mainform.date3|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row">
                                            <div class="form-group col-md-4">
                                                {{ mainform.visit_no|as_crispy_field }}
                                            </div>
                                            <div class="form-group col-md-4">
                                                {{ mainform.flu_date|as_crispy_field }}
                                            </div>
                                        </div>

                                    </div>
                                </div>



                                {% if ismainform %}
                                <div class="row justify-content-center">
                                    <div>
                                        <button type="submit" name='mainblockupdate'
                                            class="btn btn-danger mt-3">UPDATE</button>
                                    </div>
                                </div>
                                {% else %}
                                <div class="row justify-content-center">
                                    <div>
                                        <button type="submit" name='mainblocksave'
                                            class="btn btn-primary mt-3 justify-content-center">SAVE</button>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block jquery %}
<script>
    $(document).ready(function () {
        $('input[name="visit_no"]').attr('readonly', true);

        //  change date format for lmp
        $("#id_lmp").datepicker({
            format: 'dd-mm-yyyy',
        });
        $("#id_date_added").datepicker({
            format: 'dd-mm-yyyy',
        });


        $("#id_flu_date").datepicker({
            format: 'dd-mm-yyyy',
        });

        $("#id_date1").datepicker({
            format: 'dd-mm-yyyy',
        });
        $("#id_date2").datepicker({
            format: 'dd-mm-yyyy',
        });
        $("#id_date3").datepicker({
            format: 'dd-mm-yyyy',
        });


        //  set today's date for Anc first block
        ismainform = '{{ismainform}}'
        if (ismainform != 'True') {
            var today = new Date();
            var date = today.getDate() + '-' + (today.getMonth() + 1) + '-' + today.getFullYear();
            $('#id_date_added').val(date);

            //  set visit no for first block.
            $('#id_visit_no').val('1');
        }



    });
</script>
{% endblock %}

templates/records/ttdose.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-xl-10 col-lg-10">
        <div class="card shadow mb-4 mt-5 ml-5 p-4">
            <!-- Card Header  -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h2 class="m-0 font-weight-bold text-primary">Investigations & USG ({{ patient.full_name }})</h2>
                <form action="{% url 'viewpatient' patient.id %}" method="GET">
                    <button class="btn btn-warning"><i class="fas fa-arrow-left pr-3"></i>BACK</button>
                </form>
            </div>

            <!-- Card Body -->
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-danger col-md-6" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}

                <div class="navigation d-flex flex-row mb-5 mt-3 justify-content-center">
                    <div>
                        <form action="{% url 'investigations' patient_pk=patient.id %}" method="get">
                            <button class="btn btn-secondary mr-5">Investigations</button>
                        </form>
                    </div>
                    <div>
                        <form action="{% url 'usg' patient_pk=patient.id %}" method="get">
                            <button class="btn btn-secondary mr-5">USG</button>
                        </form>
                    </div>
                    <div>
                        <form action="{% url 'ttdose' patient_pk=patient.id %}" method="get">
                            <button class="btn btn-primary mr-2">TT Dose</button>
                        </form>
                    </div>
                </div>

                <form action="" method="post">
                    {% csrf_token %}
                    <div class="tt border border-success p-4 border-left-success mt-5">
                        <h3 class="text-info mt-3 font-weight-bold">TT Dose</h3>

                        <div class="col-sm-5 mt-5">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th scope="col">TT - 1st Dose</th>
                                        <th scope="col">{{ form.tt1_date|as_crispy_field }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row">TT - 2nd Dose</th>
                                        <td>{{ form.tt2_date|as_crispy_field }}</td>
                                    </tr>
                                </tbody>
                            </table>

                            {{ form.instructions|as_crispy_field }}
                        </div>
                        {% if isformexists %}
                        <button type="submit" name='update' class="btn btn-danger mt-3">UPDATE</button>
                        {% else %}
                        <button type="submit" name='save' class="btn btn-primary mt-3">SAVE</button>
                        {% endif %}
                    </div>
                </form>

                <form action="{% url 'investigationsreport' patient.id %}" method="get">
                    <button type="submit" class="btn btn-success mt-5">PRINT</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block jquery %}
<script>
    $(document).ready(function () {
        $("#id_tt1_date").datepicker({
            format: 'dd-mm-yyyy',
        });
        $("#id_tt2_date").datepicker({
            format: 'dd-mm-yyyy',
        });
    });
</script>
{% endblock %}