amhsystem/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('medicine/', include('medicine.urls')),
    path('records/', include('records.urls')),
    path('pdfs/', include('pdfs.urls')),
    path('appointment/', include('appointment.urls')),
]

appointment/urls.py
from django.urls import path
from appointment import views

urlpatterns = [
    # Appointment related
    path('addappointment/', views.addappointment, name='addappointment'),
    path('allappointments/', views.allappointments, name='allappointments'),
    path('deleteappointment/<int:apt_pk>', views.deleteappointment, name='deleteappointment'),
    # path('viewpatient/<int:patient_pk>', views.viewpatient, name='viewpatient'),
    path('fetchpatientnames', views.fetchpatientnames, name='fetchpatientnames'),

]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    # Auth
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),

    path('', views.home, name='home'),

    # Patients related
    path('allpatients/', views.allpatients, name='allpatients'),
    path('searchpatient/', views.searchpatient, name='searchpatient'),
    path('addpatient/', views.addpatient, name='addpatient'),
    path('viewpatient/<int:patient_pk>', views.viewpatient, name='viewpatient'),
    path('editpatient/<int:patient_pk>', views.editpatient, name='editpatient'),
    path('deletepatient/<int:patient_pk>', views.deletepatient, name='deletepatient'),
    path('fetchpatientnames', views.fetchpatientnames, name='fetchpatientnames'),

]

appointment/models.py
from django.db import models
from django.db.models.fields import TimeField
from main.models import Patient

# Create your models here.
class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    patient_name = models.CharField(max_length=150)
    date_added = models.DateTimeField(auto_now_add=True)
    on_date = models.DateField(blank=False)
    visit_no = models.IntegerField(blank=True, null=True)
    # at_time = models.TimeField(blank=True, null=True)
    reason = models.CharField(max_length=100, blank=True)

appointment/forms.py
from django.forms import ModelForm, widgets
from .models import Appointment


class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        

        fields = '__all__'
        exclude = ['date_added', 'patient', 'visit_no']

        widgets = {
            'on_date': widgets.DateInput(format= '%d-%m-%Y', attrs={'class':'form-control', 'autocomplete':'off', 'placeholder': 'dd-mm-yyyy'}),
         }

        labels = {
            'on_date': 'Date of Appointment',
            'reason': 'Reason',
            'patient_name': 'Appointment For',
        }

appointment/views.py
from .models import Appointment
from main.models import Patient
from .forms import AppointmentForm
from django.http import JsonResponse
from datetime import datetime
from django.contrib import messages

from django.shortcuts import get_object_or_404, render, redirect

# Create your views here.
def addappointment(request):
    form = AppointmentForm()
    if 'getpatientbyname' in request.POST:
        patientname = request.POST['patientname']
        patient = Patient.objects.get(full_name=patientname)
        form = AppointmentForm()
        return render(request, 'appointment/addappointment.html', {'form': form, 'patientname':patient.full_name, })


    if 'addappointment' in request.POST:
        patientname = request.POST['patient_name']
        on_date = request.POST['on_date']
        patient = Patient.objects.get(full_name=patientname)
        date = datetime.strptime(on_date, "%d-%m-%Y").strftime('%Y-%m-%d')
        isAptExist = Appointment.objects.filter(on_date=date, patient=patient)
        if isAptExist:
            messages.error(request, 'Duplicate Appointment! Apt for this patient on ' + on_date + ' is already added!')
            return render(request, 'appointment/addappointment.html', {'form': form, 'patientname':patient.full_name,})
        else:
            try:
                form = AppointmentForm(request.POST)
                addform = form.save(commit=False)
                addform.patient = patient
                messages.add_message(request, messages.SUCCESS, 'Appointment Added Successfully!!')
                addform.save()
            except:
                messages.error(request, 'Something went wrong!')
        return render(request, 'appointment/addappointment.html', {'form': form, 'patientname':patient.full_name,})

    
    if request.method == 'GET':
       return render(request, 'appointment/addappointment.html', {'form': form}) 


def allappointments(request):
    appointments = Appointment.objects.order_by('-date_added')
    return render(request, 'appointment/allappointments.html', {'appointments': appointments})


def deleteappointment(request, apt_pk):
    try:
        apttodelete = get_object_or_404(Appointment, pk=apt_pk)
        apttodelete.delete()
        messages.add_message(request, messages.SUCCESS, 'Appointment deleted successfully!')
        return redirect('allappointments')
    except:
        messages.add_message(request, messages.ERROR, 'Something went wrong! Try again later!')
        return redirect('allappointments')


# for autocomplete feature in add add appointment form
def fetchpatientnames(request):
    if 'term' in request.GET:
        patients = Patient.objects.filter(full_name__icontains=request.GET.get('term'))
        names = list()
        for patient in patients:
            names.append(patient.full_name)
        return JsonResponse(names, safe=False)

templates/appointment/addappointment.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-xl-10 col-lg-10">
        <div class="card shadow mb-4 mt-5 ml-5 p-4">
            <!-- Card Header  -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h3 class="m-0 font-weight-bold text-primary">Add Appointment</h3>
            </div>

            <!-- Card Body -->
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-danger col-md-6" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}
                <div class="d-flex justify-content-center">
                    <div class="col-md-6 border border-success p-4 border-left-success">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="d-flex flex-row">
                                <div class="form-group mr-4">
                                    {{ form.patient_name|as_crispy_field }}
                                </div>

                            </div>

                            <div class="d-flex flex-row">
                                <div class="form-group mr-4">
                                    {{ form.on_date|as_crispy_field }}
                                </div>
                            </div>


                            <div class="d-flex flex-row">
                                <div class="form-group flex-grow-1 mr-4">
                                    {{ form.reason|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row justify-content-center">
                                <div class="col-3">
                                    <button type="submit" name='addappointment'
                                        class="btn btn-primary mt-3 justify-content-center">ADD</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block jquery %}
<script>
    $(document).ready(function () {

        $("#id_patient_name").autocomplete({
            source: "{% url 'fetchpatientnames' %}"
        });

        $("#patientname").autocomplete({
            source: "{% url 'fetchpatientnames' %}"
        });

        // $('#id_patient_name').attr('readonly', true);
        $('#id_patient_name').val('{{ patientname }}')

        $("#id_on_date").datepicker({
            format: 'dd-mm-yyyy',
        });

    });
</script>
{% endblock %}

templates/appointment/allappointments.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-xl-10 col-lg-10">
        <div class="card shadow mb-4 mt-5 ml-5 p-4">
            <!-- Card Header  -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h3 class="m-0 font-weight-bold text-primary">All Appointments
                    {% if appointments %}
                    <small>
                        ({{ appointments.count}})
                    </small>
                    {% endif %}
                </h3>

                <div class="col-sm-3 mt-2 d-flex flex-row justify-content-end">
                    <form action="{% url 'addappointment' %}" method="GET">
                        <button class="btn btn-danger"><i class="fas fa-plus pr-2"></i>ADD NEW</button>
                    </form>
                </div>
            </div>
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-danger col-md-6" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}
                {% if appointments %}
                <div class="table-responsive">

                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Patient Name</th>
                                <th>On Date</th>
                                <th>Reason</th>
                                <th>Actions</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for appointment in appointments %}
                            <tr>
                                <td>{{appointment.patient_name}}</td>
                                <td>{{appointment.on_date}}</td>
                                <td>{{appointment.reason}}</td>
                                <td>
                                    <form action="{% url 'deleteappointment' appointment.id %}" method="GET">
                                        <button type="submit" class="btn btn-primary btn-sm" name="view"
                                            onclick="return confirm('Are you sure? Appointment will be deleted permanently.');">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <div class="text-center">
                    <h2>No Appointments Found!</h2>
                    <br>
                    <a role="button" class="btn btn-primary" href="{% url 'addappointment' %}">New Appointment</a>
                </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block jquery %}
<!-- Page level plugins -->
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/datatables-demo.js' %}"></script>
{% endblock jquery %}